Standardize README
Kitura/Kitura-redis pull request #66
Opened 2018-07-09 13:03 UTC by helenmasters

* Add standard sections which were missing
* Update header banner
* Clarify further how to use Redis

2018-07-09 15:05 UTC, djones6 requested changes

2018-07-09 15:05 UTC, djones6 commented on README.md
> +## Run Tests
It feels a bit odd to encounter this section here.  Maybe it's the title?  I might prefer something like this:
## Contributing
Contributions to the Kitura-redis project are welcome.  You will want to be able to test your changes locally before submitting a pull request.

The tests require a Redis server accessible locally on the default port (6379).  If you do not wish to install Redis permanently, you can use Docker to run a temporary instance locally as follows:
```
docker run -d -p 6379:6379 redis:alpine redis-server --requirepass password123
```
The password specified above must match the one defined in `Tests/SwiftRedis/password.txt`.  Then you can run the tests as normal, either via Xcode or with:
```
swift test
```

2018-07-10 13:15 UTC, helenmasters commented
@djones6 please can you look at the latest commit as I've addressed your review comments.

2018-07-16 12:20 UTC, djones6 approved these changes

2018-07-16 12:22 UTC, merged